version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       - MYSQL_ROOT_PASSWORD
       - MYSQL_DATABASE
       - MYSQL_USER
       - MYSQL_PASSWORD

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "${WORDPRESS_PORT}:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:${MYSQL_PORT}
       WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
       WORDPRESS_DB_USER: ${MYSQL_USER}
       WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
     volumes:
        - ./wp-content:/var/www/html/wp-content

   wordpress_cli:
     image: wordpress:cli
     user: xfs
     volumes:
       - ./wp-content:/var/www/html/wp-content
     depends_on:
       - db
       - wordpress
     command: >
        /bin/sh -c '
          until nc -z -v -w30 db 3306
          do
            sleep 5; #First wait for DB to be ready
          done

          until [ -f /var/www/html/wp-config.php ]
          do
              sleep 5 #Wait for WordPress to be installed
          done
          
          if ! $$(wp core is-installed); then
            echo "Installing WordPress, this will only take a second .. ";
            wp core install --path="/var/www/html" --url="http://localhost:${WORDPRESS_PORT}" --title="${WORDPRESS_PAGE_TITLE}" --admin_user=${WORDPRESS_ADMIN_USER} --admin_password=${WORDPRESS_ADMIN_PASSWORD} --admin_email=${WORDPRESS_ADMIN_EMAIL}
          fi
        '
volumes:
    db_data:
    wordpress: